-- Auto-generated by scripts/generate-monsters-seed.js
-- DO NOT edit by hand — re-run the script

BEGIN;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'leather',
  'Leather',
  'レザー',
  NULL,
  'small',
  '{}',
  '{}',
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Leather_Icon.png',
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'alloy',
  'Alloy',
  'アロイ',
  NULL,
  'small',
  '{}',
  '{}',
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Alloy_Icon.png',
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'bone',
  'Bone',
  '骨',
  NULL,
  'small',
  '{}',
  '{}',
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Bone_Icon.png',
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'lunar_new_year',
  'Lunar New Year',
  '旧正月',
  NULL,
  'small',
  '{}',
  '{}',
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Lunar_New_Year_Icon.png',
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'spring_festival',
  'Spring Festival',
  'スプリングフェスティバル',
  NULL,
  'small',
  '{}',
  '{}',
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Spring_Festival_Icon.png',
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'hope',
  'Hope',
  'ホープ',
  NULL,
  'small',
  '{}',
  '{}',
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Hope_Icon.png',
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'great_jagras',
  'Great Jagras',
  'ドスジャグラス',
  'bird_wyvern',
  'low',
  ARRAY['none']::TEXT[],
  ARRAY['fire', 'poison', 'paralysis', 'blast', 'sleep']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Great_Jagras_Icon.png',
  1
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'kulu_ya_ku',
  'Kulu-Ya-Ku',
  'クルルヤック',
  'bird_wyvern',
  'low',
  ARRAY['none']::TEXT[],
  ARRAY['water', 'ice']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Kulu-Ya-Ku_Icon.png',
  2
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'pukei_pukei',
  'Pukei-Pukei',
  'プケプケ',
  'bird_wyvern',
  'low',
  ARRAY['poison']::TEXT[],
  ARRAY['thunder', 'paralysis', 'sleep']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Pukei-Pukei_Icon.png',
  3
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'coral_pukei_pukei',
  'Coral Pukei-Pukei',
  'プケプケ亜種',
  'bird_wyvern',
  'high',
  ARRAY['water']::TEXT[],
  ARRAY['poison', 'ice']::TEXT[],
  true,
  'pukei_pukei',
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Coral_Pukei-Pukei_Icon.png',
  4
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'barroth',
  'Barroth',
  'ボルボロス',
  'brute_wyvern',
  'low',
  ARRAY['water']::TEXT[],
  ARRAY['fire', 'poison', 'blast']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Barroth_Icon.png',
  5
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'great_girros',
  'Great Girros',
  'ドスギルオス',
  'fanged_wyvern',
  'low',
  ARRAY['paralysis']::TEXT[],
  ARRAY['water', 'ice']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Great_Girros_Icon.png',
  6
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'tobi_kadachi',
  'Tobi-Kadachi',
  'トビカガチ',
  'fanged_wyvern',
  'low',
  ARRAY['thunder']::TEXT[],
  ARRAY['water', 'ice']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Tobi-Kadachi_Icon.png',
  7
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'viper_tobi_kadachi',
  'Viper Tobi-Kadachi',
  'トビカガチ亜種',
  'fanged_wyvern',
  'high',
  ARRAY['paralysis', 'poison']::TEXT[],
  ARRAY['thunder']::TEXT[],
  true,
  'tobi_kadachi',
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Viper_Tobi-Kadachi_Icon.png',
  8
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'paolumu',
  'Paolumu',
  'パオウルムー',
  'flying_wyvern',
  'high',
  ARRAY['none']::TEXT[],
  ARRAY['fire', 'blast']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Paolumu_Icon.png',
  9
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'nightshade_paolumu',
  'Nightshade Paolumu',
  'パオウルムー亜種',
  'flying_wyvern',
  'high',
  ARRAY['sleep']::TEXT[],
  ARRAY['fire', 'thunder']::TEXT[],
  true,
  'paolumu',
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Nightshade_Paolumu_Icon.png',
  10
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'jyuratodus',
  'Jyuratodus',
  'ジュラトドス',
  'piscine_wyvern',
  'low',
  ARRAY['water']::TEXT[],
  ARRAY['thunder']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Jyuratodus_Icon.png',
  11
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'anjanath',
  'Anjanath',
  'アンジャナフ',
  'brute_wyvern',
  'low',
  ARRAY['fire']::TEXT[],
  ARRAY['water', 'ice']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Anjanath_Icon.png',
  12
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'fulgur_anjanath',
  'Fulgur Anjanath',
  'アンジャナフ亜種',
  'brute_wyvern',
  'high',
  ARRAY['thunder']::TEXT[],
  ARRAY['ice', 'water']::TEXT[],
  true,
  'anjanath',
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Fulgar-Anjanath_Icon.png',
  13
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'rathian',
  'Rathian',
  'リオレイア',
  'flying_wyvern',
  'high',
  ARRAY['fire']::TEXT[],
  ARRAY['dragon', 'thunder']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Rathian_Icon.png',
  14
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'pink_rathian',
  'Pink Rathian',
  'リオレイア亜種',
  'flying_wyvern',
  'high',
  ARRAY['fire', 'poison']::TEXT[],
  ARRAY['dragon', 'thunder']::TEXT[],
  true,
  'rathian',
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Pink_Rathian_Icon.png',
  15
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'gold_rathian',
  'Gold Rathian',
  'リオレイア希少種',
  'flying_wyvern',
  'high',
  ARRAY['fire', 'poison']::TEXT[],
  ARRAY['thunder']::TEXT[],
  true,
  'rathian',
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Gold_Rathian_Icon.png',
  16
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'legiana',
  'Legiana',
  'レイギエナ',
  'flying_wyvern',
  'high',
  ARRAY['ice']::TEXT[],
  ARRAY['poison', 'fire']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Legiana_Icon.png',
  17
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'diablos',
  'Diablos',
  'ディアブロス',
  'flying_wyvern',
  'high',
  ARRAY['none']::TEXT[],
  ARRAY['ice', 'dragon', 'paralysis']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Diablos_Icon.png',
  18
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'black_diablos',
  'Black Diablos',
  'ディアブロス亜種',
  'flying_wyvern',
  'high',
  ARRAY['none']::TEXT[],
  ARRAY['ice', 'paralysis']::TEXT[],
  true,
  'diablos',
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Black_Diablos_Icon.png',
  19
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'rathalos',
  'Rathalos',
  'リオレウス',
  'flying_wyvern',
  'high',
  ARRAY['fire', 'poison']::TEXT[],
  ARRAY['dragon', 'thunder']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Rathalos_Icon.png',
  20
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'azure_rathalos',
  'Azure Rathalos',
  'リオレウス亜種',
  'flying_wyvern',
  'high',
  ARRAY['fire', 'poison']::TEXT[],
  ARRAY['dragon', 'ice']::TEXT[],
  true,
  'rathalos',
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Azure_Rathalos_Icon.png',
  21
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'silver_rathalos',
  'Silver Rathalos',
  'リオレウス希少種',
  'flying_wyvern',
  'high',
  ARRAY['fire']::TEXT[],
  ARRAY['water', 'thunder']::TEXT[],
  true,
  'rathalos',
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Silver_Rathalos_Icon.png',
  22
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'radobaan',
  'Radobaan',
  'ラドバルキン',
  'brute_wyvern',
  'high',
  ARRAY['sleep']::TEXT[],
  ARRAY['dragon', 'ice', 'poison', 'blast']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Radobaan_Icon.png',
  23
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'banbaro',
  'Banbaro',
  'バフバロ',
  'brute_wyvern',
  'high',
  ARRAY['none']::TEXT[],
  ARRAY['dragon', 'fire', 'blast']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Banbaro_Icon.png',
  24
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'barioth',
  'Barioth',
  'ベリオロス',
  'flying_wyvern',
  'high',
  ARRAY['ice']::TEXT[],
  ARRAY['fire']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Barioth_Icon.png',
  25
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'zinogre',
  'Zinogre',
  'ジンオウガ',
  'fanged_wyvern',
  'high',
  ARRAY['thunder']::TEXT[],
  ARRAY['ice']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Zinogre_Icon.png',
  26
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'tzitzi_ya_ku',
  'Tzitzi-Ya-Ku',
  'ツィツィヤック',
  'bird_wyvern',
  'low',
  ARRAY['none']::TEXT[],
  ARRAY['ice']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Tzitzi-Ya-Ku_Icon.png',
  28
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'odogaron',
  'Odogaron',
  'オドガロン',
  'fanged_wyvern',
  'high',
  ARRAY['none']::TEXT[],
  ARRAY['ice', 'paralysis']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Odogaron_Icon.png',
  29
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'ebony_odogaron',
  'Ebony Odogaron',
  'オドガロン亜種',
  'fanged_wyvern',
  'high',
  ARRAY['dragon']::TEXT[],
  ARRAY['water', 'poison', 'paralysis']::TEXT[],
  true,
  'odogaron',
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Ebony_Odogaron_Icon.png',
  30
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'deviljho',
  'Deviljho',
  'デビルジョー',
  'brute_wyvern',
  'high',
  ARRAY['dragon']::TEXT[],
  ARRAY['thunder', 'dragon', 'poison']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Deviljho_Icon.png',
  31
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'basarios',
  'Basarios',
  'バサリオス',
  'flying_wyvern',
  'high',
  ARRAY['fire']::TEXT[],
  ARRAY['water', 'dragon']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Basarios_Icon.png',
  32
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'khezu',
  'Khezu',
  'フルフル',
  'flying_wyvern',
  'high',
  ARRAY['thunder', 'paralysis']::TEXT[],
  ARRAY['fire', 'poison']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Khezu_Icon.png',
  33
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'mizutsune',
  'Mizutsune',
  'タマミツネ',
  'leviathan',
  'high',
  ARRAY['water']::TEXT[],
  ARRAY['thunder', 'dragon']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Mizutsune_Icon.png',
  34
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'kushala_daora',
  'Kushala Daora',
  'クシャルダオラ',
  'elder_dragon',
  'elder',
  ARRAY['ice']::TEXT[],
  ARRAY['thunder', 'dragon', 'blast', 'poison']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Kushala_Daora_Icon.png',
  35
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'teostra',
  'Teostra',
  'テオ・テスカトル',
  'elder_dragon',
  'elder',
  ARRAY['fire', 'blast']::TEXT[],
  ARRAY['water', 'ice']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Teostra_Icon.png',
  36
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'aknosom',
  'Aknosom',
  'アケノシルム',
  'bird_wyvern',
  'high',
  ARRAY['fire']::TEXT[],
  ARRAY['water', 'ice']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Aknosom_Icon.png',
  37
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'magnamalo',
  'Magnamalo',
  'マガイマガド',
  'fanged_wyvern',
  'high',
  ARRAY['blast']::TEXT[],
  ARRAY['water', 'dragon']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Magnamalo_Icon.png',
  38
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'rajang',
  'Rajang',
  'ラージャン',
  'fanged_beast',
  'high',
  ARRAY['thunder']::TEXT[],
  ARRAY['ice']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Rajang_Icon.png',
  39
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'nergigante',
  'Nergigante',
  'ネルギガンテ',
  'elder_dragon',
  'elder',
  ARRAY['none']::TEXT[],
  ARRAY['thunder', 'blast']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Nergigante_Icon.png',
  40
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'lagombi',
  'Lagombi',
  'ウルクスス',
  'fanged_beast',
  'low',
  ARRAY['ice']::TEXT[],
  ARRAY['fire', 'poison', 'blast', 'paralysis']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Lagombi_Icon.png',
  41
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'volvidon',
  'Volvidon',
  'ラングロトラ',
  'fanged_beast',
  'high',
  ARRAY['fire']::TEXT[],
  ARRAY['water', 'ice']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Volvidon_Icon.png',
  42
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'somnacanth',
  'Somnacanth',
  'イソネミクニ',
  'leviathan',
  'high',
  ARRAY['sleep']::TEXT[],
  ARRAY['thunder']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Somnacanth_Icon.png',
  43
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'beotodus',
  'Beotodus',
  'ブラントドス',
  'piscine_wyvern',
  'low',
  ARRAY['ice']::TEXT[],
  ARRAY['fire', 'blast']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Beotodus_Icon.png',
  44
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'tigrex',
  'Tigrex',
  'ティガレックス',
  'flying_wyvern',
  'high',
  ARRAY['none']::TEXT[],
  ARRAY['thunder', 'dragon']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Tigrex_Icon.png',
  45
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'brute_tigrex',
  'Brute Tigrex',
  'ティガレックス亜種',
  'brute_wyvern',
  'high',
  ARRAY['none']::TEXT[],
  ARRAY['water', 'thunder']::TEXT[],
  true,
  'tigrex',
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Brute-Tigrex_Icon.jpg',
  46
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'kirin',
  'Kirin',
  'キリン',
  'elder_dragon',
  'elder',
  ARRAY['thunder']::TEXT[],
  ARRAY['fire', 'dragon']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Kirin_Icon.png',
  47
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'bazelgeuse',
  'Bazelgeuse',
  'バゼルギウス',
  'flying_wyvern',
  'high',
  ARRAY['fire']::TEXT[],
  ARRAY['thunder']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Bazelgeuse_Icon.png',
  48
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'chatacabra',
  'Chatacabra',
  'チャタカブラ',
  'fanged_wyvern',
  'low',
  ARRAY['none']::TEXT[],
  ARRAY['thunder']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Chatacabra_Icon.png',
  49
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'arzuros',
  'Arzuros',
  'アオアシラ',
  'fanged_beast',
  'low',
  ARRAY['none']::TEXT[],
  ARRAY['fire', 'poison', 'blast', 'paralysis', 'sleep']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Arzuros_Icon.png',
  50
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'glavenus',
  'Glavenus',
  'ディノバルド',
  'brute_wyvern',
  'high',
  ARRAY['fire']::TEXT[],
  ARRAY['water', 'thunder']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Glavenus_Icon.png',
  51
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'chameleos',
  'Chameleos',
  'オオナズチ',
  'elder_dragon',
  'elder',
  ARRAY['poison']::TEXT[],
  ARRAY['fire', 'dragon']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Chameleos_Icon.png',
  52
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'wroggi',
  'Wroggi',
  'ドスフロギィ',
  'bird_wyvern',
  'low',
  ARRAY['poison']::TEXT[],
  ARRAY['ice', 'paralysis', 'sleep']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Great_Wroggi_Icon.png',
  53
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'bishaten',
  'Bishaten',
  'ビシュテンゴ',
  'fanged_beast',
  'high',
  ARRAY['paralysis', 'poison']::TEXT[],
  ARRAY['ice']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Bishaten_Icon.png',
  54
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'namielle',
  'Namielle',
  'ネロミェール',
  'elder_dragon',
  'elder',
  ARRAY['water']::TEXT[],
  ARRAY['fire', 'dragon', 'poison', 'blast']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Namielle_Icon.png',
  55
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'nargacuga',
  'Nargacuga',
  'ナルガクルガ',
  'fanged_wyvern',
  'high',
  ARRAY['none']::TEXT[],
  ARRAY['thunder']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Nargacuga_Icon.png',
  56
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'lunagaron',
  'Lunagaron',
  'ルナガロン',
  'fanged_wyvern',
  'high',
  ARRAY['ice']::TEXT[],
  ARRAY['fire']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Lunagaron_Icon.png',
  57
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'espinas',
  'Espinas',
  'エスピナス',
  'flying_wyvern',
  'high',
  ARRAY['fire', 'poison', 'paralysis']::TEXT[],
  ARRAY['ice', 'dragon']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Espinas_Icon.png',
  58
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'malzeno',
  'Malzeno',
  'メルゼナ',
  'elder_dragon',
  'elder',
  ARRAY['none']::TEXT[],
  ARRAY['dragon']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Malzeno_Icon.png',
  59
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'quematrice',
  'Quematrice',
  'ケマトリス',
  'flying_wyvern',
  'high',
  ARRAY['fire']::TEXT[],
  ARRAY['water', 'ice']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Quematrice_Icon.png',
  60
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'garangolm',
  'Garangolm',
  'ガランゴルム',
  'brute_wyvern',
  'high',
  ARRAY['none']::TEXT[],
  ARRAY['thunder']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Garangolm_Icon.png',
  61
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'goss_harag',
  'Goss Harag',
  'ゴシャハギ',
  'fanged_beast',
  'high',
  ARRAY['ice']::TEXT[],
  ARRAY['fire']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Goss_Harag_Icon.png',
  62
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'astalos',
  'Astalos',
  'ライゼクス',
  'flying_wyvern',
  'high',
  ARRAY['thunder', 'paralysis']::TEXT[],
  ARRAY['ice']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Astalos_Icon.png',
  63
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'seregios',
  'Seregios',
  '千刃竜',
  'flying_wyvern',
  'high',
  ARRAY['none']::TEXT[],
  ARRAY['thunder']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Seregios_Icon.png',
  64
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'almudron',
  'Almudron',
  '泥翁龍',
  'leviathan',
  'high',
  ARRAY['water']::TEXT[],
  ARRAY['fire']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Almudron_Icon.png',
  65
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'stygian_zinogre',
  'Stygian Zinogre',
  'ジンオウガ亜種',
  'fanged_wyvern',
  'high',
  ARRAY['dragon']::TEXT[],
  ARRAY['thunder', 'blast']::TEXT[],
  true,
  'zinogre',
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Stygian_Zinogre_Icon.png',
  27
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'shogun_ceanataur',
  'Shogun Ceanataur',
  'ショウグンギザミ',
  'carapaceon',
  'high',
  ARRAY['water']::TEXT[],
  ARRAY['thunder']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Shogun_Ceanataur_Icon.png',
  66
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'velkhana',
  'Velkhana',
  'イヴェルカーナ',
  'elder_dragon',
  'elder',
  ARRAY['ice']::TEXT[],
  ARRAY['fire', 'dragon', 'blast']::TEXT[],
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Velkhana_Icon.png',
  67
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'mrbeast',
  'MrBeast',
  'MrBeast',
  NULL,
  'low',
  ARRAY['none']::TEXT[],
  '{}',
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-MrBeast_Icon.png',
  68
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'happy_hunting_new_year',
  'Happy Hunting New Year',
  'ハッピーハンティングニューイヤー',
  NULL,
  'small',
  '{}',
  '{}',
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Happy_Hunting_New_Year_Icon.png',
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'halloween',
  'Halloween',
  'ハロウィン',
  NULL,
  'small',
  '{}',
  '{}',
  false,
  NULL,
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Halloween_Icon.png',
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.monsters
  (id, name, name_ja, species, tier, elements, weaknesses, is_variant, parent_id, games, is_active, icon, sort_order)
VALUES (
  'radiant_great_girros',
  'Radiant Great Girros',
  '',
  'fanged_wyvern',
  'low',
  '{}',
  ARRAY['dragon', 'sleep']::TEXT[],
  true,
  'great_girros',
  ARRAY['mhn']::TEXT[],
  TRUE,
  '/images/monsters/MHNow-Radiant_Great_Girros_Icon.png',
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  name_ja = EXCLUDED.name_ja,
  species = COALESCE(public.monsters.species, EXCLUDED.species),
  tier = EXCLUDED.tier,
  elements = EXCLUDED.elements,
  weaknesses = EXCLUDED.weaknesses,
  is_variant = EXCLUDED.is_variant,
  parent_id = EXCLUDED.parent_id,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order;

COMMIT;