-- Auto-generated by scripts/generate-skills-seed.cjs
-- DO NOT edit by hand — re-run the script

BEGIN;

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'rude_awakener',
  'Rude Awakener',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'poison_resistance',
  'Poison Resistance',
  NULL,
  'defense',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'concentration',
  'Concentration',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'critical_eye',
  'Critical Eye',
  NULL,
  'critical',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'ice_resistance',
  'Ice Resistance',
  NULL,
  'defense',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'attack_boost',
  'Attack Boost',
  NULL,
  'attack',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'fire_resistance',
  'Fire Resistance',
  NULL,
  'defense',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'defense_boost',
  'Defense Boost',
  NULL,
  'defense',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'thunder_resistance',
  'Thunder Resistance',
  NULL,
  'defense',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'health_boost',
  'Health Boost',
  NULL,
  'defense',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'water_resistance',
  'Water Resistance',
  NULL,
  'defense',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'paralysis_resistance',
  'Paralysis Resistance',
  NULL,
  'defense',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'earplugs',
  'Earplugs',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'tremor_resistance',
  'Tremor Resistance',
  NULL,
  'defense',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'lock_on',
  'Lock On',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":1}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'windproof',
  'Windproof',
  NULL,
  'defense',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'firm_foothold',
  'Firm Foothold',
  NULL,
  'defense',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'fighting_spirit',
  'Fighting Spirit',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'water_attack',
  'Water Attack',
  NULL,
  'attack',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'fortify',
  'Fortify',
  NULL,
  'survival',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'guts',
  'Guts',
  NULL,
  'survival',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'last_stand',
  'Last Stand',
  NULL,
  'survival',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'evade_extender',
  'Evade Extender',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'sneak_attack',
  'Sneak Attack',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'focus',
  'Focus',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'poison_attack',
  'Poison Attack',
  NULL,
  'attack',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'weakness_exploit',
  'Weakness Exploit',
  NULL,
  'critical',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'power_prolonger',
  'Power Prolonger',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'skyward_striker',
  'Skyward Striker',
  NULL,
  'attack',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'reload_speed',
  'Reload Speed',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'recoil_down',
  'Recoil Down',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'offensive_guard',
  'Offensive Guard',
  NULL,
  'attack',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'guard',
  'Guard',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'paralysis_attack',
  'Paralysis Attack',
  NULL,
  'attack',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'artful_dodger',
  'Artful Dodger',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'thunder_attack',
  'Thunder Attack',
  NULL,
  'attack',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'divine_blessing',
  'Divine Blessing',
  NULL,
  'defense',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'fire_attack',
  'Fire Attack',
  NULL,
  'attack',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'special_boost',
  'Special Boost',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'peak_performance',
  'Peak Performance',
  NULL,
  'attack',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'critical_element',
  'Critical Element',
  NULL,
  'attack',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'burst',
  'Burst',
  NULL,
  'attack',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'ice_attack',
  'Ice Attack',
  NULL,
  'attack',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'heroics',
  'Heroics',
  NULL,
  'attack',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'slugger',
  'Slugger',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'partbreaker',
  'Partbreaker',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'resentment',
  'Resentment',
  NULL,
  'attack',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'dragon_attack',
  'Dragon Attack',
  NULL,
  'attack',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'critical_boost',
  'Critical Boost',
  NULL,
  'critical',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'solidarity',
  'Solidarity',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":1}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'sleep_attack',
  'Sleep Attack',
  NULL,
  'attack',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'sleep_resistance',
  'Sleep Resistance',
  NULL,
  'defense',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'bleeding_resistance',
  'Bleeding Resistance',
  NULL,
  'defense',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'latent_power',
  'Latent Power',
  NULL,
  'attack',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'artillery',
  'Artillery',
  NULL,
  'attack',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'resuscitate',
  'Resuscitate',
  NULL,
  'status',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'bubbly_dance',
  'Bubbly Dance',
  NULL,
  'status',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'blast_attack',
  'Blast Attack',
  NULL,
  'attack',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'blast_resistance',
  'Blast Resistance',
  NULL,
  'defense',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'ballistics',
  'Ballistics',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'spare_shot',
  'Spare Shot',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'aggressive_dodger',
  'Aggressive Dodger',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'dauntless',
  'Dauntless',
  NULL,
  'survival',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'offensive_dodger',
  'Offensive Dodger',
  NULL,
  'attack',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'evasive_concentration',
  'Evasive Concentration',
  NULL,
  'utility',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'special_insurance',
  'Special Insurance',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":1}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'hellfire_cloak',
  'Hellfire Cloak',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'morph_boost',
  'Morph Boost',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'morph_attack_boost',
  'Morph Attack Boost',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'evading_reload',
  'Evading Reload',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'frostwind',
  'Frostwind',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'teostra_powder',
  'Teostra Powder',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'nergigante_hunger',
  'Nergigante Hunger',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'chameleos_venomist',
  'Chameleos Venomist',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'namielle_power',
  'Namielle Power',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'malzeno_crimsonblood',
  'Malzeno Crimsonblood',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'defensive_loading',
  'Defensive Loading',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'final_strike',
  'Final Strike',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'blunt_force',
  'Blunt Force',
  NULL,
  'attack',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'buildup_boost',
  'Buildup Boost',
  NULL,
  'status',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'blood_cloak',
  'Blood Cloak',
  NULL,
  'survival',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'perfectionist',
  'Perfectionist',
  NULL,
  'utility',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'pursuit',
  'Pursuit',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'poison_exploit',
  'Poison Exploit',
  NULL,
  'status',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'paralysis_exploit',
  'Paralysis Exploit',
  NULL,
  'status',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'kirin_flashstorm',
  'Kirin Flashstorm',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'critical_ferocity',
  'Critical Ferocity',
  NULL,
  'critical',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'special_partbreaker',
  'Special Partbreaker',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'vital_thunder',
  'Vital Thunder',
  NULL,
  'health',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'raw_power',
  'Raw Power',
  NULL,
  'attack',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'quick_work',
  'Quick Work',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'fortitude',
  'Fortitude',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'litheness',
  'Litheness',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'guard_up',
  'Guard Up',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":1}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'advanced_attack_boost',
  'Advanced Attack Boost',
  NULL,
  'attack',
  ARRAY['mhn']::TEXT[],
  '{"mhn":2}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'advanced_ice_attack',
  'Advanced Ice Attack',
  NULL,
  'attack',
  ARRAY['mhn']::TEXT[],
  '{"mhn":2}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'advanced_thunder_attack',
  'Advanced Thunder Attack',
  NULL,
  'attack',
  ARRAY['mhn']::TEXT[],
  '{"mhn":2}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'rapid_swim_2025',
  'Rapid Swim 2025',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'summer_passion_2025',
  'Summer Passion 2025',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'vital_ice',
  'Vital Ice',
  NULL,
  'health',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'vital_fire',
  'Vital Fire',
  NULL,
  'health',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'dragon_boost',
  'Dragon Boost',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'solidarity_winter',
  'Solidarity Winter',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'shared_sword',
  'Shared Sword',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'shared_shield',
  'Shared Shield',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'balloon_collision',
  'Balloon Collision',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'egg_burst',
  'Egg Burst',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'happy_new_year',
  'Happy New Year',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'hunter_unity',
  'Hunter Unity',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'reckless',
  'Reckless',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'combo_master',
  'Combo Master',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'advanced_burst',
  'Advanced Burst',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":2}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'vital_water',
  'Vital Water',
  NULL,
  'health',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'slicing_ammo_boost',
  'Slicing Ammo Boost',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'advanced_water_attack',
  'Advanced Water Attack',
  NULL,
  'attack',
  ARRAY['mhn']::TEXT[],
  '{"mhn":2}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'tail_partbreaker',
  'Tail Partbreaker',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":1}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'advanced_dragon_attack',
  'Advanced Dragon Attack',
  NULL,
  'attack',
  ARRAY['mhn']::TEXT[],
  '{"mhn":2}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'elemental_release',
  'Elemental Release',
  NULL,
  'attack',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'vital_dragon',
  'Vital Dragon',
  NULL,
  'health',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'attack_efficacy',
  'Attack Efficacy',
  NULL,
  'attack',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'critical_strength',
  'Critical Strength',
  NULL,
  'critical',
  ARRAY['mhn']::TEXT[],
  '{"mhn":1}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'velkhana_aegis',
  'Velkhana Aegis',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'meditation',
  'Meditation',
  NULL,
  'utility',
  ARRAY['mhn']::TEXT[],
  '{"mhn":5}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

INSERT INTO public.skills
  (id, name, name_ja, category, games, max_levels, is_active, icon, sort_orders, notes, description)
VALUES (
  'normal_element_ammo_boost',
  'Normal Element Ammo Boost',
  NULL,
  'general',
  ARRAY['mhn']::TEXT[],
  '{"mhn":3}'::JSONB,
  TRUE,
  NULL,
  '{}'::JSONB,
  NULL,
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  max_levels = COALESCE(public.skills.max_levels, EXCLUDED.max_levels),
  games = COALESCE(public.skills.games, EXCLUDED.games);

COMMIT;
